### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zicochaos** [GPudgima/YT-SONOS#9]
Had this error 

Uncaught Exception:
Error: ffmpeg exited with code 1: /private/var/folders/m1/85btvr1d0gz6fhpyp1dhgtrr0000gn/T/AppTranslocation/1943199F-6237-404E-AB70-977F4D23FB94/d/YT-SONOS.app/Contents/Resources/app/server/stream/1.mp3: Read-only file system

    at ChildProcess.<anonymous> (/private/var/folders/m1/85btvr1d0gz6fhpyp1dhgtrr0000gn/T/AppTranslocation/1943199F-6237-404E-AB70-977F4D23FB94/d/YT-SONOS.app/Contents/Resources/app/server/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:203:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

**Comment by GPudgima** [comment]
Hey @zicochaos,

Thanks for opening this. What release are you using? Are there any steps you can take to recreate this? 

Thanks.

**Comment by zicochaos** [comment]
hi, I'm using YT-Sonos-0.4.0-Beta. No steps needed. Download, unpack, move to the Applications folder and run.

**Comment by GPudgima** [comment]
@zicochaos 
> hi, I'm using YT-Sonos-0.4.0-Beta. No steps needed. Download, unpack, move to the Applications folder and run.

Interesting. What OS are you running on? From the error it appears something is trying to access it at multiple times - for example:
_if you run the program, try to send a video and play the music file from a media player at the same time, it will throw this error._

Do you just run the program and it comes up with the error or is it when you are inputting a YT video?

**Comment by GPudgima** [comment]
@zicochaos I'm going to close this assuming it's worked its self out. 
IF you happen to have this again, please resubmit. 

Thanks.
